name: On PR or push to main

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**.yml'
      - 'src/**'
  pull_request:
    paths:
      - '.github/workflows/**.yml'
      - 'src/**'

env:
  BAZEL_TARGET: 1 # https://stackoverflow.com/a/73429959/1975086

jobs:

  pnpm-install-and-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: git rev-parse HEAD
      - run: git rev-parse HEAD~1

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install PNPM
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT
      #         echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - name: Cache PNPM store directory
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - run: pnpm install
        working-directory: ./src

  build:
    needs: pnpm-install-and-cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: git rev-parse HEAD
      - run: git rev-parse HEAD~1

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install PNPM
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT
      #         echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - name: Cache PNPM store directory
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - run: pnpm install
        working-directory: ./src

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3

      - name: nx lint affected
        # run: pnpm run nx run-many --all --target=lint
        run: pnpm run nx affected --target=lint --base=${{ env.NX_BASE }}
        working-directory: ./src

      - name: nx build affected
        # https://stackoverflow.com/questions/73876647/using-nx-run-many-shows-another-process-with-id-is-currently-running-ngcc
        run: pnpm run nx affected --target=build --base=${{ env.NX_BASE }} --parallel=1
        working-directory: ./src
